# theme: jekyll-theme-leap-day
theme: minima
title: "Hilario Esparza"
include: ["index.md"]
description: "Project Documentation"

header_pages:
  - Pages/courses.md
  - Pages/projects.md
  - index.md

markdown: kramdown
kramdown:
  math_engine: mathjax
